name: Java CI with Maven

on:
  push:
    branches: [ "main"]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Mavend and Run Back unit test 
      run: |
       mvn verify
      working-directory: ./projetcac-back
    - name : Run Front unit test
      run: |
       npm install
       npm run test:unit
      working-directory: ./projetcac-front 
